/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId/index'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgOrgIdTeamTeamIdIndexRouteImport } from './routes/org/$orgId/team/$teamId/index'
import { Route as OrgOrgIdTeamTeamIdTodosRouteImport } from './routes/org/$orgId/team/$teamId/todos'
import { Route as OrgOrgIdTeamTeamIdPagesRouteImport } from './routes/org/$orgId/team/$teamId/pages'
import { Route as OrgOrgIdTeamTeamIdBlocksRouteImport } from './routes/org/$orgId/team/$teamId/blocks'
import { Route as OrgOrgIdTeamTeamIdPagesPageIdRouteImport } from './routes/org/$orgId/team/$teamId/pages/$pageId'
import { Route as OrgOrgIdTeamTeamIdBlocksBlockIdRouteImport } from './routes/org/$orgId/team/$teamId/blocks/$blockId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/org/$orgId/',
  path: '/org/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdIndexRoute = OrgOrgIdTeamTeamIdIndexRouteImport.update({
  id: '/org/$orgId/team/$teamId/',
  path: '/org/$orgId/team/$teamId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdTodosRoute = OrgOrgIdTeamTeamIdTodosRouteImport.update({
  id: '/org/$orgId/team/$teamId/todos',
  path: '/org/$orgId/team/$teamId/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdPagesRoute = OrgOrgIdTeamTeamIdPagesRouteImport.update({
  id: '/org/$orgId/team/$teamId/pages',
  path: '/org/$orgId/team/$teamId/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdBlocksRoute =
  OrgOrgIdTeamTeamIdBlocksRouteImport.update({
    id: '/org/$orgId/team/$teamId/blocks',
    path: '/org/$orgId/team/$teamId/blocks',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdPagesPageIdRoute =
  OrgOrgIdTeamTeamIdPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => OrgOrgIdTeamTeamIdPagesRoute,
  } as any)
const OrgOrgIdTeamTeamIdBlocksBlockIdRoute =
  OrgOrgIdTeamTeamIdBlocksBlockIdRouteImport.update({
    id: '/$blockId',
    path: '/$blockId',
    getParentRoute: () => OrgOrgIdTeamTeamIdBlocksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/blocks': typeof OrgOrgIdTeamTeamIdBlocksRouteWithChildren
  '/org/$orgId/team/$teamId/pages': typeof OrgOrgIdTeamTeamIdPagesRouteWithChildren
  '/org/$orgId/team/$teamId/todos': typeof OrgOrgIdTeamTeamIdTodosRoute
  '/org/$orgId/team/$teamId/': typeof OrgOrgIdTeamTeamIdIndexRoute
  '/org/$orgId/team/$teamId/blocks/$blockId': typeof OrgOrgIdTeamTeamIdBlocksBlockIdRoute
  '/org/$orgId/team/$teamId/pages/$pageId': typeof OrgOrgIdTeamTeamIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/blocks': typeof OrgOrgIdTeamTeamIdBlocksRouteWithChildren
  '/org/$orgId/team/$teamId/pages': typeof OrgOrgIdTeamTeamIdPagesRouteWithChildren
  '/org/$orgId/team/$teamId/todos': typeof OrgOrgIdTeamTeamIdTodosRoute
  '/org/$orgId/team/$teamId': typeof OrgOrgIdTeamTeamIdIndexRoute
  '/org/$orgId/team/$teamId/blocks/$blockId': typeof OrgOrgIdTeamTeamIdBlocksBlockIdRoute
  '/org/$orgId/team/$teamId/pages/$pageId': typeof OrgOrgIdTeamTeamIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/blocks': typeof OrgOrgIdTeamTeamIdBlocksRouteWithChildren
  '/org/$orgId/team/$teamId/pages': typeof OrgOrgIdTeamTeamIdPagesRouteWithChildren
  '/org/$orgId/team/$teamId/todos': typeof OrgOrgIdTeamTeamIdTodosRoute
  '/org/$orgId/team/$teamId/': typeof OrgOrgIdTeamTeamIdIndexRoute
  '/org/$orgId/team/$teamId/blocks/$blockId': typeof OrgOrgIdTeamTeamIdBlocksBlockIdRoute
  '/org/$orgId/team/$teamId/pages/$pageId': typeof OrgOrgIdTeamTeamIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/profile'
    | '/signup'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/images/$'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/blocks'
    | '/org/$orgId/team/$teamId/pages'
    | '/org/$orgId/team/$teamId/todos'
    | '/org/$orgId/team/$teamId/'
    | '/org/$orgId/team/$teamId/blocks/$blockId'
    | '/org/$orgId/team/$teamId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/profile'
    | '/signup'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/images/$'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId/blocks'
    | '/org/$orgId/team/$teamId/pages'
    | '/org/$orgId/team/$teamId/todos'
    | '/org/$orgId/team/$teamId'
    | '/org/$orgId/team/$teamId/blocks/$blockId'
    | '/org/$orgId/team/$teamId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/profile'
    | '/signup'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/images/$'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/blocks'
    | '/org/$orgId/team/$teamId/pages'
    | '/org/$orgId/team/$teamId/todos'
    | '/org/$orgId/team/$teamId/'
    | '/org/$orgId/team/$teamId/blocks/$blockId'
    | '/org/$orgId/team/$teamId/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdTeamTeamIdBlocksRoute: typeof OrgOrgIdTeamTeamIdBlocksRouteWithChildren
  OrgOrgIdTeamTeamIdPagesRoute: typeof OrgOrgIdTeamTeamIdPagesRouteWithChildren
  OrgOrgIdTeamTeamIdTodosRoute: typeof OrgOrgIdTeamTeamIdTodosRoute
  OrgOrgIdTeamTeamIdIndexRoute: typeof OrgOrgIdTeamTeamIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/': {
      id: '/org/$orgId/team/$teamId/'
      path: '/org/$orgId/team/$teamId'
      fullPath: '/org/$orgId/team/$teamId/'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/todos': {
      id: '/org/$orgId/team/$teamId/todos'
      path: '/org/$orgId/team/$teamId/todos'
      fullPath: '/org/$orgId/team/$teamId/todos'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/pages': {
      id: '/org/$orgId/team/$teamId/pages'
      path: '/org/$orgId/team/$teamId/pages'
      fullPath: '/org/$orgId/team/$teamId/pages'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/blocks': {
      id: '/org/$orgId/team/$teamId/blocks'
      path: '/org/$orgId/team/$teamId/blocks'
      fullPath: '/org/$orgId/team/$teamId/blocks'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/pages/$pageId': {
      id: '/org/$orgId/team/$teamId/pages/$pageId'
      path: '/$pageId'
      fullPath: '/org/$orgId/team/$teamId/pages/$pageId'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdPagesPageIdRouteImport
      parentRoute: typeof OrgOrgIdTeamTeamIdPagesRoute
    }
    '/org/$orgId/team/$teamId/blocks/$blockId': {
      id: '/org/$orgId/team/$teamId/blocks/$blockId'
      path: '/$blockId'
      fullPath: '/org/$orgId/team/$teamId/blocks/$blockId'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdBlocksBlockIdRouteImport
      parentRoute: typeof OrgOrgIdTeamTeamIdBlocksRoute
    }
  }
}

interface OrgOrgIdTeamTeamIdBlocksRouteChildren {
  OrgOrgIdTeamTeamIdBlocksBlockIdRoute: typeof OrgOrgIdTeamTeamIdBlocksBlockIdRoute
}

const OrgOrgIdTeamTeamIdBlocksRouteChildren: OrgOrgIdTeamTeamIdBlocksRouteChildren =
  {
    OrgOrgIdTeamTeamIdBlocksBlockIdRoute: OrgOrgIdTeamTeamIdBlocksBlockIdRoute,
  }

const OrgOrgIdTeamTeamIdBlocksRouteWithChildren =
  OrgOrgIdTeamTeamIdBlocksRoute._addFileChildren(
    OrgOrgIdTeamTeamIdBlocksRouteChildren,
  )

interface OrgOrgIdTeamTeamIdPagesRouteChildren {
  OrgOrgIdTeamTeamIdPagesPageIdRoute: typeof OrgOrgIdTeamTeamIdPagesPageIdRoute
}

const OrgOrgIdTeamTeamIdPagesRouteChildren: OrgOrgIdTeamTeamIdPagesRouteChildren =
  {
    OrgOrgIdTeamTeamIdPagesPageIdRoute: OrgOrgIdTeamTeamIdPagesPageIdRoute,
  }

const OrgOrgIdTeamTeamIdPagesRouteWithChildren =
  OrgOrgIdTeamTeamIdPagesRoute._addFileChildren(
    OrgOrgIdTeamTeamIdPagesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdTeamTeamIdBlocksRoute: OrgOrgIdTeamTeamIdBlocksRouteWithChildren,
  OrgOrgIdTeamTeamIdPagesRoute: OrgOrgIdTeamTeamIdPagesRouteWithChildren,
  OrgOrgIdTeamTeamIdTodosRoute: OrgOrgIdTeamTeamIdTodosRoute,
  OrgOrgIdTeamTeamIdIndexRoute: OrgOrgIdTeamTeamIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
